blank_issues_enabled: false
contact_links:
  - name: Flow Store
    url: https://github.com/itskartike910/extensions/blob/main/.github/ISSUE_TEMPLATE/new-extension.md
    about: Please read our documentation before submitting an extension.